groundlight/framegrab

- pyproject.toml
- src/framegrab/motion.py
This PR ensures that we flag motion as detected in case we get a new image with dimensions differing from the previous image's dimensions.
> Flag Motion Detection if New Image has Different Dimensions

- README.md
- pyproject.toml
- src/framegrab/grabber.py
> Autodiscover

- README.md
- pyproject.toml
- src/framegrab/grabber.py
**Background:**
https://positronixcorp.atlassian.net/browse/PK-2140
When creating grabbers on a Linux machine, framegrab attempts to find the serial numbers of the plugged in devices by running some terminal commands via Python. This is done in GenericUSBFrameGrabber._find_cameras. If no devices are plugged in, the program crashes.
Need to add some better error handling for this situation.
Steps to reproduce, on a Linux machine (e.g. Jetson) that does not have any cameras plugged in, run `ls /dev/video*`. You will get an error. In the Python code, this ends up causing an exception to be raised on this line `idx = int(re.findall(r"\d+", devname)[-1])`
**Solution:**
Now when no cameras are plugged in, FrameGrabber.autodiscover returns an empty dictionary
> adding handling for autodiscover when no cameras are plugged in

- src/framegrab/grabber.py
The convention for autogenerating grabber names has changed.
Previously, with each autogenerated name, a counter was incremented, e.g. Unnamed USB Camera 1, Unnamed USB Camera 2. This led to some undesirable behavior on the URCap, because each time the user hits the refresh cameras button, the cameras that weren't explicitly named in the config got a new name, causing the program to break the next time you run it.
The new convention is to use the serial number or some other unique identifier (ip address) in the autogenerated name. This way, the autogenerated name will be the same every time.
Additionally, the behavior of warmup_delay has changed. It is no longer in the config, but rather a parameter in create_grabber, create_grabbers and autodiscover. This has the following benefits:
- …
> Autogenerate grabber names + changes to warmup_delay

- pyproject.toml
Addressing issue kindly reported by a user here: https://github.com/groundlight/framegrab/issues/19
> Add GH repo link to PyPi page

- pyproject.toml
- src/framegrab/grabber.py
Previously, if an RTSP FrameGrabber object was running in your script, you would get a threading error if you tried to terminate the script with crtl+c.
This PR adds handling to avoid this error and exit gracefully.
> Fixing threading error when exiting program with ctrl+c

- pyproject.toml
- src/framegrab/cli/autodiscover.py
- src/framegrab/cli/clitools.py
- src/framegrab/cli/preview.py
A bit of refactoring in the CLI tools for preview & autodiscover so they're more robust and useful.  Autodiscover will preview the images it finds with `imgcat` by default.
> CLI improvements - autodiscover previews images, is more robust

- sample_scripts/sample_config.yaml
- src/framegrab/grabber.py
Addressing issue: https://github.com/groundlight/framegrab/issues/30
As long as each RTSP config has a unique password placeholder, then we'll be able to look it up in the list of environment variables and use it. This means, we can have a config like this:
```yaml
image_sources:
- name: Front Door
input_type: generic_usb
options: 
zoom:
digital: 1.5
- name: Conference Room
input_type: rtsp
id: 
rtsp_url: rtsp://admin:{{CAM1_RTSP_PASSWORD}}@10.0.0.0/cam/realmonitor?channel=1&subtype=0
options:
crop:
relative:
top: .1
bottom: .9
left: .1
right: .9
- name: Second Conference Room
input_type: rtsp
id: 
rtsp_url: rtsp://admin:{{CAM2_RTSP_PASSWORD}}@10.0.0.0/cam/realmonitor?channel=1&subtype=0
options:
crop:
relative:
top: .1
bottom: .9
left: .1
right: .9
```
> Allow Environment Variable Substitution for RTSP URLs

- src/framegrab/grabber.py
Not an incredibly big change, but we got uninformative errors on some rtsp streams that seemingly connect but won't supply any data stream. We could alternatively provide a stronger check earlier instead of just asking that `self.capture.isOpened()`, though it's not clear we would have a means of correcting it here.
> handle edge case

- README.md
- pyproject.toml
- src/framegrab/grabber.py
This allows you to specify if you want to keep the connection open to your RTSP stream while not actively grabbing. While that makes the frame grab quicker, if you want to grab from many different camera streams then keeping many connections open can potentially strain your network resources. So now in your camera options you can specify "keep_camera_connection_open" to either True or False. It will default to True if not provided.
I made a new class OnDemandRTSPFrameGrabber for clarity sake. I found that was much cleaner than adding extra logic to check the flag since their init methods differ significantly.
> On demand grabber

- README.md
- src/framegrab/grabber.py
- test/test_framegrab_with_mock_camera.py
Previously, when a user did not provide an RTSP URL for an RTSP grabber, it raised this exception: 
```
raise ValueError("RTSP URL should contain exactly one placeholder for the password.")
```
It would be more helpful to raise an exception that says "please provide an RTSP URL"
I adjusted the order of the guard clauses to allow this to happen.
I also made it possible for users to _not_ use password substitution. I believe some users might want to just have passwords in their yaml, which as far as I know, is okay.
I changed `_substitute_rtsp_password` to be a static method because it didn't actually use self, and I wanted to write a test for it without having to create an instance of the class.
I added a few tests for the changes I made.
> Fixing RTSP Grabber Exception Handling

- pyproject.toml
- src/framegrab/grabber.py
Orin Nanos are able to see IR cameras on webcams such as the Logitech Brio. Because of this, they will actually grab the IR camera instead of the color camera, which produces not-so-useful images. Interestingly, Xaviers do not see the IR camera, so it's not an issue there. Sunil also reported this issue on a Raspberry Pi in https://github.com/groundlight/framegrab/issues/26. 
On Orin Nano:
```sh
$ ls /dev/video*
/dev/video0  /dev/video1  /dev/video2  /dev/video3
```
On Xavier:
```sh
$ ls /dev/video*
/dev/video1  /dev/video2
```
To fix this, we will skip an devices that have a name of "Logitech Brio" and produce grayscale frames. This is kind of a special case fix, but it seems like the best thing to do for now. If we discover any other cameras with this same behavior, we can update the …
> Fix for IR cameras

- pyproject.toml
- src/framegrab/cli/autodiscover.py
- src/framegrab/cli/clitools.py
- src/framegrab/grabber.py
This PR added support for RTSP discovery in the built-in `FrameGrabber.autodiscover()` function and also can be called in CLI.
> Added support for RTSP discovery in autodiscover and CLI

- pyproject.toml
- src/framegrab/rtsp_discovery.py
Small PR change to support higher pydantic version for other projects that requires a higher version.
> Updated pydantic version range to support higher version

- pyproject.toml
- src/framegrab/rtsp_discovery.py
This PR tries to solve an issue for WSDiscovery that is still binding the socket after it has been instantiated. This PR provides a workaround by creating a singleton object for WSDiscovery so that it does not instantiate more than once.
> Added Workaround for WSDiscovery Bug

- README.md
- pyproject.toml
The example yaml usage in the readme had a couple problems:
1) Indentation error in the yaml
2) it used an outdated way of loading the yaml, not leveraging the newer `FrameGrabber.from_yaml` method.
This PR fixes both issues.
> Fix YAML example in readme

- pyproject.toml
- src/framegrab/grabber.py
Currently, if a user creates a `FrameGrabber` object and supplies a config that contains a resolution, the resolution will be updated each time the `grab` method is called via `_set_cv2_resolution`. This is bad because it is a non-trivial operation and can significantly slow down grabbing.
This PR adds logic to check if the resolution in the config is new and only updates if it is new.
> Better logic for updating cv2.VideoCapture resolution

- pyproject.toml
- src/framegrab/grabber.py
We've discussed previously that it would make more sense to rotate the image _before_ cropping. I am finding this to be very much the case as I am adding panning capabilities to the URCap. This PR simply changes that.
> Moving the rotate operation before cropping

- .github/workflows/auto-format.yaml
- .github/workflows/tests.yaml
- README.md
- pyproject.toml
- sample_scripts/sample_config.yaml
- src/framegrab/cli/autodiscover.py
- src/framegrab/cli/preview.py
- src/framegrab/grabber.py
- src/framegrab/motion.py
- test/test_framegrab_with_hls.py
- test/test_framegrab_with_mock_camera.py
Add support for HTTP Live Streaming (HLS) and YouTube Live videos (which is just HLS under the hood).
Also do some general cleanup:
1. remove unused imports
2. clean up motion detection documentation
3. support optional extra dependency installation
4. move from python 3.7 -> python 3.9 (oldest version that is not out of service)
> Add HLS and YouTube Live support.

- pyproject.toml
- src/framegrab/grabber.py
- test/test_framegrab_with_filestream.py
"Its better to ask forgiveness than permission"
The check for a local path was too strict - in fact sometimes this will fail when cv2 would have no issue reading the file - eg over a network. We should only fail here when cv2 actually throws an exception.
> Reduce strictness of file path validation

- pyproject.toml
- src/framegrab/__init__.py
- src/framegrab/grabber.py
- test/test_framegrab_with_filestream.py
- test/test_framegrab_with_mock_camera.py
Previously, if even one grabber config was invalid (wrong rtsp url, camera was unplugged, etc.) in `create_grabbers`, an exception would be raised.
I do not believe this is correct behavior, and it is causing problems on the URCap: if one of the user-configured cameras cannot connect for whatever reason, all of the configured cameras fail to connect. This PR changes the behavior so that a warning is logged, and all cameras that successfully connected are returned. 
I debated making this change for a while, because I thought it might lead to silent failures, but I realized that the client can just compare the list of configs to the resulting grabbers to learn if there were any connection failures (which is what I plan to do on the URCap).
> Handle case where one grabber config is invalid in `create_grabbers`

- pyproject.toml
- src/framegrab/grabber.py
`wsdiscovery`, a depedency of framegrab calls `logging.basicConfig`, which is not good. This will override an logging configurations that framegrab users attempt to set. This PR removes that config.
Here is some output from my machine that pointed me towards the fact that `wsdicovery` was calling `logging.basicConfig`
```
tim@tim:~/gl-demo$ grep -r "basicConfig" $(poetry env info --path)/lib/python*/site-packages/
/home/tim/gl-demo/.venv/lib/python3.11/site-packages/wsdiscovery/cmdline.py:logging.basicConfig()
/home/tim/gl-demo/.venv/lib/python3.11/site-packages/wsdiscovery/asynch.py:logging.basicConfig()
```
> Undoing wsdiscovery's logging configuration

- src/framegrab/grabber.py
- test/test_all_grabber_types_generic.py
The pydantic changes didn't allow the user to directly pass the config dictionary into the constructor. We want the changes to be backwards compatible so I fixed this. This fixes the bug in the readme creating a youtube grabber.
> Fix framegrab bug passing dictionary directly into the constructor

- pyproject.toml
- src/framegrab/grabber.py
- test/test_framegrab_with_mock_camera.py
When performing rotation operations, framegrab returns a non-contiguous array. For many uses, this is okay, but I realized functions like cv2.line will fail on this.
I change the rotation operation from `np.rot90` to `cv2.rotate`. This avoids the non-contiguous problem and is also more performant.
> Output contiguous arrays when rotating frames
